image: ruby:2.6

variables:
  JEKYLL_ENV: production

cache:
  paths:
  - vendor/

pages:
  stage: deploy
  script:
    - curl -o _data/regnum.json https://scripts.drachenwald.sca.org/json/regnum-officers-box.json
    - bundle install --path vendor
    - bundle exec jekyll build -d public
    - ./_ci/cf-clear.sh
  artifacts:
    expire_in: 1 hour
    paths:
      - public
  only:
    - staging
